### ISSUE TITLE
pygmsh

### ISSUE THREAD

**Issue by nschloe** [tridelat/py2gmsh#2]
You might want to check https://github.com/nschloe/pygmsh, it seems quite similar to this project here.

**Comment by tridelat** [comment]
@nschloe That's right, it's quite similar, as they both produce geo files.
The main difference, if I got this right (and correct me if I am wrong), is that `pygmsh` provides premade functions to create geometries using its own syntax, while `py2gmsh` is providing an OOP way to define geo files using a syntax as close as possible to the gmsh scripting language syntax. The idea of `py2gmsh` is to be able to create completely arbitrary geometries from scratch, kind of the gmsh way (but object-oriented). There is also a function that can be used to translate arbitrary geometries defined with vertices, segments, facets, etc into a full `Mesh` object, which is particularly useful for a project like https://github.com/erdc/proteus , where geometries are often defined outside of gmsh. Actually, `py2gmsh` was mostly created because of needs for that project.
I see that `pygmsh` has evolved quite a bit since `py2gmsh` was created as well, so there are more crossovers now. The OpenCASCADE part of `pygmsh` looks useful, I haven't actually used this in gmsh.
Maybe it would make sense to join forces somehow?

**Comment by nschloe** [comment]
Yeah, I think the two projects are really similar. Just wanted to make sure you're aware! :+1:
